# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistname', models.CharField(max_length=200)),
                ('albumart', models.CharField(max_length=200)),
                ('playlisttype', models.CharField(default='CREATED', max_length=200)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
