# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_playlistsongs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistsongs',
            old_name='song',
            new_name='url',
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='albumart',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='songname',
            field=models.CharField(default=datetime.datetime(2018, 5, 2, 13, 58, 19, 93838, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='videoid',
            field=models.CharField(default=datetime.datetime(2018, 5, 2, 13, 58, 33, 130222, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
